### ISSUE TITLE
Please add attribution for OSeMOSYS

### ISSUE THREAD

**Issue by willu47** [ClimateCompatibleGrowth/osemosys_kenya#6]
As you have included the osemosys code in `wesm/model_wesm.txt` and `psm/model_psm.txt`, you should include the Apache 2.0 license, and also explain in the file and the readme that these are a derivative of the original OSeMOSYS framework, cite the paper, and link back to the OSeMOSYS/OSeMOSYS_GNU_MathProg repository.

**Comment by pielube** [comment]
Done.
