### ISSUE TITLE
Archive the software to Zenodo upon release

### ISSUE THREAD

**Issue by willu47** [ClimateCompatibleGrowth/osemosys_kenya#8]
You can find a guideline on how to archive code automatically to Zenodo on the [CCG guidelines website](https://climatecompatiblegrowth.github.io/guidelines/code/2021/01/01/archiving-code.html)

**Comment by pielube** [comment]
Not sure how to do that, as in this repo we store both the PSM and WESM, that tend to have separate releases. Maybe we should have two separate repos?

**Comment by willu47** [comment]
Yes, it is a good idea to separate out models which have different release cycles. On the other hand if the PSM is only used in the WESM then keeping them in one repo could work.

**Comment by pielube** [comment]
I have created two separate repositories. The WESM repo should be ok, while I'll work on the PSM one later on. I have archived the first version of the WESM (v0.1.0) on Zenodo, linking  GitHub and Zenodo.
